# Generated by Django 3.0.8 on 2020-07-20 19:50

from django.db import migrations, models
import django.db.models.deletion
import landingpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_field', models.CharField(max_length=256)),
                ('caption_field', models.CharField(max_length=254)),
                ('body_text', models.TextField()),
                ('date_field', models.TextField(max_length=12)),
            ],
            options={
                'verbose_name': 'blog post',
                'verbose_name_plural': 'blog posts',
                'ordering': ('date_field',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=150)),
                ('category_slug', models.SlugField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='contact_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=256)),
                ('email_field', models.EmailField(max_length=254)),
                ('message_text', models.TextField(max_length=1024)),
                ('date_field', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ('date_field',),
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254)),
                ('subject_field', models.CharField(max_length=256)),
                ('message_body', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('replied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=250, unique=True)),
                ('delivered_to', models.EmailField(max_length=254)),
                ('email_from', models.EmailField(max_length=254)),
                ('subject_field', models.CharField(max_length=256)),
                ('message_body', models.TextField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('original_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Inbox Email',
                'verbose_name_plural': 'Inbox Emails',
                'ordering': ('original_date',),
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=landingpage.models.product.image_folder_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='landingpage.category')),
            ],
            options={
                'ordering': ('product_name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='splash_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splash_heading', models.CharField(max_length=512)),
                ('splash_img', models.CharField(blank=True, max_length=512)),
                ('splash_bg_color', models.CharField(blank=True, max_length=200)),
                ('splash_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'splash post',
                'verbose_name_plural': 'splash posts',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('replied', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reply', to='landingpage.contact_me')),
            ],
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_images', models.ImageField(upload_to=landingpage.models.Product_images.image_path)),
                ('image_name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('product_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_images', to='landingpage.product')),
            ],
            options={
                'verbose_name': 'product images',
                'verbose_name_plural': 'product images',
            },
        ),
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_product', models.PositiveIntegerField()),
                ('cart_foreign', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Add_to_cart', to='landingpage.Cart')),
                ('product_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Add_to_cart', to='landingpage.product')),
            ],
            options={
                'verbose_name': 'updated cart',
                'verbose_name_plural': 'updated carts',
            },
        ),
    ]
