# Generated by Django 3.0.8 on 2020-07-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsreader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_content',
            options={'verbose_name': 'Article links to pull article data from', 'verbose_name_plural': 'Article links to pull article data from'},
        ),
        migrations.AlterModelOptions(
            name='article_links',
            options={'verbose_name': 'Link to article', 'verbose_name_plural': 'Links to articles'},
        ),
        migrations.AlterModelOptions(
            name='article_site',
            options={'verbose_name': 'Site to pull article links from', 'verbose_name_plural': 'Sites to pull article links from'},
        ),
        migrations.AlterField(
            model_name='article_site',
            name='language',
            field=models.CharField(choices=[('XML', 'XML'), ('HTML', 'HTML')], default='HTML', max_length=4),
        ),
    ]
