# Generated by Django 3.0.8 on 2020-07-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsreader', '0002_auto_20200718_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_site',
            name='webste_type',
            field=models.CharField(choices=[('XML', 'XML'), ('HTML', 'HTML')], default='HTML', max_length=4),
        ),
        migrations.AlterField(
            model_name='article_site',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('SO', 'Somali')], default='EN', max_length=2),
        ),
    ]
