# Generated by Django 3.0.8 on 2020-07-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsreader', '0004_auto_20200718_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_site',
            old_name='name',
            new_name='domain',
        ),
    ]
