# Generated by Django 3.0.8 on 2020-07-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsreader', '0005_auto_20200719_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_site',
            name='domain',
            field=models.CharField(max_length=80),
        ),
    ]
