# Generated by Django 3.0.8 on 2020-07-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsreader', '0006_auto_20200719_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_site',
            old_name='webste_type',
            new_name='website_type',
        ),
    ]
