# Generated by Django 3.0.8 on 2020-07-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsreader', '0007_auto_20200719_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_links',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
