# Generated by Django 3.0.8 on 2020-07-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsreader', '0008_auto_20200719_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_links',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
