# Generated by Django 3.0.8 on 2020-07-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsreader', '0010_auto_20200719_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_links',
            options={'verbose_name': 'A Link to an article', 'verbose_name_plural': 'Links to articles'},
        ),
    ]
