# Generated by Django 3.0.8 on 2020-07-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsreader', '0011_auto_20200719_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_content',
            options={'verbose_name': 'Article link to pull article data from', 'verbose_name_plural': 'Article links to pull article data from'},
        ),
        migrations.AddField(
            model_name='article_links',
            name='scrapped',
            field=models.BooleanField(default=False),
        ),
    ]
