# Generated by Django 3.0.8 on 2020-07-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsreader', '0012_auto_20200720_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_content',
            options={'verbose_name': 'Article Data', 'verbose_name_plural': 'Article Data'},
        ),
        migrations.AlterField(
            model_name='article_content',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
